spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prototype
    username: postgres
    password: 123
    hikari:
      schema: inventory
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:migration/
    enabled: true
    schemas: inventory

rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: guest
  template:
    exchange: umut.exchange
    queue: umut.queue
    routing-key: umut.routingkey
    routing:
      json:
        key: umut.routing.json
#default-receive-queue: