
create table if not exists receipt
(
    id                bigint generated by default as identity
        primary key,
    buyer_address     varchar(255),
    buyer_tax_office  varchar(255),
    dealer_address    varchar(255),
    dealer_name       varchar(255),
    dealer_tax_office varchar(255),
    receiver_name     varchar(255)
);

create table if not exists product
(
    product_id    bigint generated by default as identity
        primary key,
    country_code  varchar(255),
    producer_name varchar(255),
    product_count varchar(255),
    product_name  varchar(255),
    product_value integer not null,
    receipt_id    bigint
        constraint fkeoaxt4slq51cis1e0v436gh2p
            references receipt
);
create table if not exists shoppingsite
(
    shopping_id   bigint generated by default as identity
        primary key,
    sale_price    integer,
    shopping_site varchar(255),
    product_id    bigint
        constraint fkf4fk1329hk7rb2070pgrrf05f
            references product
);
